# Generated by Django 4.2.7 on 2024-01-27 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_bank_totalasset_alter_transfer_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='to_account',
            new_name='to_account_id',
        ),
    ]
